name: Continuous Integration for grpc directory
on:
  push:
    paths:
      - '.github/workflows/ci-for-grpc.yaml'
      - 'grpc/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Earthly
        uses: earthly/actions-setup@v1.0.1
        with:
          version: 0.6.1
      - name: Run lint
        working-directory: grpc
        run: earthly --ci +lint

  test:
    name: Unit test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Earthly
        uses: earthly/actions-setup@v1.0.1
        with:
          version: 0.6.1
      - name: Run unit test
        working-directory: grpc
        run: earthly --ci +test

  docker:
    name: Build and push docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Earthly
        uses: earthly/actions-setup@v1.0.1
        with:
          version: 0.6.1
      - name: Login to ghcr.io
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        working-directory: grpc
        run: |
          TAG="$(date +%Y%m%d-%H%M)-$(git rev-parse --short=10 HEAD)"
          earthly --ci --push +docker --build-arg DOCKER_TAG=$TAG
