name: Continuous Integration for grpc directory
on:
  push:
    paths:
      - '.github/workflows/ci-for-grpc.yaml'
      - 'grpc/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Earthly
        uses: earthly/actions-setup@v1.0.1
        with:
          version: v0.6.20
      - name: Use Cache
        uses: actions/cache@preview
        with:
          path: ./grpc/go/pkg/mod
          key: go-${{ hashFiles('grpc/go.sum') }}
      - name: Run lint
        working-directory: grpc
        run: earthly --ci --remote-cache=ghcr.io/emiksk/earthly-example-cache:cache +lint --USE_CACHE_COMMAND=true

  test:
    name: Unit test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Earthly
        uses: earthly/actions-setup@v1.0.1
        with:
          version: v0.6.20
      - name: Use Cache
        uses: actions/cache@preview
        with:
          path: ./grpc/go/pkg/mod
          key: go-${{ hashFiles('grpc/go.sum') }}
      - name: Run unit test
        working-directory: grpc
        run: earthly --ci --remote-cache=ghcr.io/emiksk/earthly-example-cache:cache +test --USE_CACHE_COMMAND=true

  docker:
    name: Build and push docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Earthly
        uses: earthly/actions-setup@v1.0.1
        with:
          version: v0.6.20
      - name: Use Cache
        uses: actions/cache@preview
        with:
          path: ./grpc/go/pkg/mod
          key: go-${{ hashFiles('grpc/go.sum') }}
      - name: Login to ghcr.io
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Execute +deps
        working-directory: grpc
        run: earthly --ci --output --remote-cache=ghcr.io/emiksk/earthly-example-cache:cache +deps --USE_CACHE_COMMAND=true
      - name: Build and push docker image
        working-directory: grpc
        run: |
          TAG="$(date +%Y%m%d-%H%M)-$(git rev-parse --short=10 HEAD)"
          earthly --ci --push --remote-cache=ghcr.io/emiksk/earthly-example-cache:cache +docker --USE_CACHE_COMMAND=true
